---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myacart-frontend
  namespace: {{ .Values.nsname }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.mylabels | indent 6 }}
  replicas: {{ .Values.replica }}
  minReadySeconds: 6
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: myappfe
        image: mohanraz81/cart-frontend:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.3"
            memory: "300Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MY_DB_USER"
            value: "mysqluser"
          - name: "MY_DB_PASS"
            value: "password"
          - name: "MY_DB_NAME"
            value: "mydatadb"
          - name: "MY_DB_HOST_WRITE"
            value: "mysql-0.mysql"
          - name: "MY_DB_HOST_READ"
            value: "mysql-read"



